request_timeout_ms = 1000
channel_id = 'HeightRetrace'
scan_wait_s = 5

[visualizer]
component = true
class = 'afspm.components.visualizer.Visualizer'
scan_id = 'Scan2d'
subscriber = 'sub'
control_client = 'ui_client'  # TODO: Do we need this?

[translator]
component = true
class = 'translator.DriftImageTranslator'

physical_origin = 'full_scan_origin'
physical_size = 'full_scan_size'
physical_units = 'our_phys_units'
data_units = 'data_units'

channel_id = 'channel_id'

scan_time_s = 2
move_time_s = 1

drift_rate = [2.5, -1.0]
spatial_units = 'our_phys_units'
temporal_units = 's'
