# This file holds the Asylum actions.

[start-scan]
method = 'afspm.components.microscope.translators.asylum.actions.request_action'
method_name = 'DoScanFunc'
params = ['DoScan']
type = 'PASS_KWARGS'
pass_self = true

[stop-scan]
method = 'afspm.components.microscope.translators.asylum.actions.request_action'
method_name = 'DoScanFunc'
params = ['StopScan']
type = 'PASS_KWARGS'
pass_self = true

[start-spec]
method = 'afspm.components.microscope.translators.asylum.actions.request_action'
method_name = 'DoForceFunc'
params = ['Single']
type = 'PASS_KWARGS'
pass_self = true

[stop-spec]
method = 'afspm.components.microscope.translators.asylum.actions.request_action'
method_name = 'DoForceFunc'
params = ['Stop']
type = 'PASS_KWARGS'
pass_self = true

[move-spec]
method = 'afspm.components.microscope.translators.asylum.actions.request_action'
method_name = 'DoForceFunc'
params = ['Go']
type = 'PASS_KWARGS'
pass_self = true
