# This file holds the Asylum parameters. Feel free to modify the
# parameter range if you want to constrain it further.

# ----- Physical Scan Parameters ----- #
[scan-top-left-x]
uuid = 'XOffset'
unit = 'm'
type = 1.0
range = [-3.5e-5, 3.5e-5]  # [-3.5um, 3.5um]
# But really, the scan size + offset must be less than 90 um.

[scan-top-left-y]
uuid = 'YOffset'
unit = 'm'
type = 1.0
range = [-3.5e-5, 3.5e-5]  # TODO: Update range!

[scan-angle]
uuid = 'ScanAngle'
unit = 'degrees'
type = 1.0
range = [-360.0, 360.0]  # Will return in range [0, 360]

[scan-size-x]
setter = 'afspm.components.microscope.translators.asylum.params.set_scan_size_x'
getter = 'afspm.components.microscope.translators.asylum.params.get_scan_size_x'
unit = 'm'
type = 1.0
range = [0, 9e-5]  # [0 nm, 90 um]

[scan-size-y]
setter = 'afspm.components.microscope.translators.asylum.params.set_scan_size_y'
getter = 'afspm.components.microscope.translators.asylum.params.get_scan_size_y'
unit = 'm'
type = 1.0
range = [0, 9e-5]  # [0 nm, 90 um]


# ----- Digital Scan Parameters ----- #
[scan-resolution-x]  # Unitless, no range enforced.
uuid = 'ScanPoints'
type = 1
range = [32, 1536]  # > 2000 may not save

[scan-resolution-y]  # Unitless, no range enforced.
uuid = 'ScanLines'
type = 1
range = [32, 1536]  # > 2000 may not save, real max is 4096.
# Note: the supported values is some strange set. Keep in mind, your
# chosen resolution will be converted to a supported value.

# ----- Feedback Parameters ----- #
[zctrl-setpoint]
uuid = 'SetPoint'
unit = 'V'  # Note: units are V, but it may make sense to consider unitless?
type = 1.0
range = [0, 10]  # TODO: Validate. This is allowed but probably crazy!

[zctrl-pgain]  # Unitless, no range enforced.
uuid = 'ProportionalGain'
type = 1.0
range = [0, 4096]

[zctrl-igain]  # Unitless, no range enforced.
uuid = 'IntegralGain'
type = 1.0
range = [0, 4096]

# ----- Sample Slope Correction ----- #
# (There is no sample slope correction on Asylum, apparently).

# ----- Probe / Scan Parameters ----- #
[scan-speed]
uuid = 'ScanSpeed'
unit = 'm/s'
type = 1.0
range = [0, 5e-4]  # [0 m/s, 500 um / s].  Actual max is 1 m/s!

# ----- Probe Parameters ----- #
[probe-pos-x]
getter = 'afspm.components.microscope.translators.asylum.params.get_probe_pos_x'
setter = 'afspm.components.microscope.translators.asylum.params.set_probe_pos_x'
unit = 'm'
type = 1.0
range = [0, 9e-5]  # [0 nm, 90 um]
# Really: within the size of your scan (this is in scan CS).

[probe-pos-y]
getter = 'afspm.components.microscope.translators.asylum.params.get_probe_pos_y'
setter = 'afspm.components.microscope.translators.asylum.params.set_probe_pos_y'
unit = 'm'
type = 1.0
range = [0, 9e-5]  # [0 nm, 90 um]
# Really: within the size of your scan (this is in scan CS).

# ----- Other ----- #
# (There is no bias voltage, apparently).


# ----- Asylum-Specific Parameters ----- #
# The following parameters are Asylum-specific, used for some internal logic.
# We use this rather than hard-coded values in params.py, because it is
# *slightly* more convenient. Particularly, we can differentiate between
# parameters with the same SPM-specific UUID, but different 'types' (the type
# defines whether we call GV/SV for values or GS/PS for strings).
#
# The 'generic' uuids (dictionary keys) match the names of AsylumParam.

# (For scan size things)
[SCAN_SIZE]
uuid = 'ScanSize'
# No units (uses SCAN_SIZE_X/SCAN_SIZE_Y)
type = 1.0

[X_RATIO]
uuid = 'FastRatio'
# No units
type = 1.0

[Y_RATIO]
uuid = 'SlowRatio'
# No units
type = 1.0

# Miscellaneous
[IMG_PATH]
uuid = 'SaveImage'
type = ''

[SAVING_MODE]
uuid = 'SaveImage'
type = 1.0

[SCANNING_MODE]
uuid = 'LastScan'
type = 1.0
