# This file holds the Asylum parameters. Feel free to modify the
# parameter range if you want to constrain it further.

# ----- Physical Scan Parameters ----- #
[scan-top-left-x]
uuid = 'XOffset'
unit = 'm'
type = 1.0
range = [-11000.0, 11000.0]  # TODO: Update range!

[scan-top-left-y]
uuid = 'YOffset'
unit = 'm'
type = 1.0
range = [-11000.0, 11000.0]  # TODO: Update range!

[scan-angle]
uuid = 'Rotation'
unit = 'degrees'
type = 1.0
range = [-360.0, 360.0]  # TODO: Verify!

[scan-size-x]
setter = 'afspm.components.microscope.translators.asylum.params.set_scan_size_x'
getter = 'afspm.components.microscope.translators.asylum.params.get_scan_size_x'
unit = 'm'
type = 1.0
range = [-11000.0, 11000.0]  # TODO: Update range!

[scan-size-y]
setter = 'afspm.components.microscope.translators.asylum.params.set_scan_size_y'
getter = 'afspm.components.microscope.translators.asylum.params.get_scan_size_y'
unit = 'm'
type = 1.0
range = [-11000.0, 11000.0]  # TODO: Update range!


# ----- Digital Scan Parameters ----- #
[scan-resolution-x]  # Unitless, no range enforced.
uuid = 'ScanPoints'
type = 1
range = [0, 32000]  # TODO: VERIFY/UPDATE

[scan-resolution-y]  # Unitless, no range enforced.
uuid = 'ScanLines'
type = 1
range = [0, 32000]  # TODO: VERIFY/UPDATE

# ----- Feedback Parameters ----- #
# NOTE: Update zctrl channel in AsylumTranslator constructor.
[zctrl-setpoint]  # TODO: Update!
uuid = 'dsp-fbs-mx0-current-set'
type = 1.0
range = [-100, 100]  # TODO: Validate

[zctrl-pgain]  # Unitless, no range enforced.
uuid = 'ProportionalGain'
type = 1.0
range = [0, 200]  # TODO: Validate

[zctrl-igain]  # Unitless, no range enforced.
uuid = 'IntegralGain'
type = 1.0
range = [0, 200]  # TODO: Validate

# ----- Sample Slope Correction ----- #
[sample-slope-x]  # TODO: Update!!!
uuid = 'dsp-adv-scan-slope-x'  # TODO: test 'dsp-mk2-hwi-slope-x'
type = 1.0
range = [-0.2, 0.2]

[sample-slope-y]  # TODO: Update!!!
uuid = 'dsp-adv-scan-slope-y'  # TODO: test 'dsp-mk2-hwi-slope-y'
type = 1.0
range = [-0.2, 0.2]

# ----- Probe / Scan Parameters ----- #
[scan-speed]
uuid = 'ScanSpeed'
unit = 'm/s'
type = 1.0
range = [0.1, 10000]  # TODO: Validate range!

[move-speed]  # TODO: Update!
uuid = 'MoveSpeed'
unit = 'm/s'
type = 1.0
range = [0.1, 10000]  # TODO: Validate

# ----- Probe Parameters ----- #
[probe-pos-x]
getter = 'afspm.components.microscope.translators.asylum.params.get_probe_pos_x'
setter = 'afspm.components.microscope.translators.asylum.params.set_probe_pos_x'
unit = 'm'
type = 1.0
range = [-11000.0, 11000.0]  # TODO: Update

[probe-pos-y]  # TODO: Validate this is correct!
getter = 'afspm.components.microscope.translators.asylum.params.get_probe_pos_y'
setter = 'afspm.components.microscope.translators.asylum.params.set_probe_pos_y'
unit = 'm'
type = 1.0
range = [-11000.0, 11000.0]  # TODO: update

# ----- Other ----- #
# [tip-bias-voltage]


# ----- Asylum-Specific Parameters ----- #
# The following parameters are Asylum-specific, used for some internal logic.
# We use this rather than hard-coded values in params.py, because it is
# *slightly* more convenient. Particularly, we can differentiate between
# parameters with the same SPM-specific UUID, but different 'types' (the type
# defines whether we call GV/SV for values or GS/PS for strings).
#
# The 'generic' uuids (dictionary keys) match the names of AsylumParam.

# (For scan size things)
[SCAN_SIZE]
uuid = 'ScanSize'
# No units (uses SCAN_SIZE_X/SCAN_SIZE_Y)
type = 1.0

[X_RATIO]
uuid = 'FastRatio'
# No units
type = 1.0

[Y_RATIO]
uuid = 'SlowRatio'
# No units
type = 1.0

# Miscellaneous
[IMG_PATH]
uuid = 'SaveImage'
type = ''

[SPEC_PATH]
uuid = 'SaveForce'
type = ''

[SAVE_IMAGE]
uuid = 'SaveImage'
type = 1.0

[SAVE_FORCE]
uuid = 'SaveForce'
type = 1.0
