# This file holds the GXSM actions.

[start-scan]
method = 'gxsm.startscan'

[stop-scan]
method = 'gxsm.stopscan'

[start-spec]
method = 'gxsm.action'
uuid = 'DSP_VP_FZ_EXECUTE'
type = 'PASS_ARGS'

[stop-spec]
method = 'gxsm.action'
uuid = 'DSP_VP_ABORT_EXECUTE'
type = 'PASS_ARGS'
